import { RequestHooksProvider, RequestHooksProviderProps } from '@boilerplate-frontend/utils';
import { ReactRenderer } from '@storybook/react';
import { DecoratorFunction } from 'storybook/internal/csf';
import {
  mockPerformanceOverPeriods,
  mockRentabilityHistory,
  mockRentabilityOverPeriods,
  mockStockEarningsOverPeriods,
  mockWithdrawalDepositsOverPeriods,
  netWorthMock,
  performanceOverPeriodMock,
  securityPositionByClassMock,
} from '../../mocks/mocks';

export const withRequestHooksProvider: DecoratorFunction<ReactRenderer> = (Story) => {
  const providerProps: RequestHooksProviderProps = {
    useFetchNetWorthOverPeriods: () => ({
      data: netWorthMock,
      dataUpdatedAt: Date.now(),
      error: null,
      errorUpdateCount: 0,
      errorUpdatedAt: Date.now(),
      isError: false,
      isFetched: true,
      isFetching: false,
      isFetchedAfterMount: true,
      isInitialLoading: false,
      isLoading: false,
      isLoadingError: false,
      isPaused: false,
      isRefetching: false,
      isRefetchError: false,
      isPending: false,
      isSuccess: true,
      isStale: false,
      status: 'success',
      failureCount: 0,
      failureReason: null,
      fetchStatus: 'idle',
      refetch: () =>
        new Promise(() => {
          return;
        }),
    }),
    useFetchPerformanceOverPeriod: () => ({
      data: performanceOverPeriodMock,
      dataUpdatedAt: Date.now(),
      error: null,
      errorUpdateCount: 0,
      errorUpdatedAt: Date.now(),
      isError: false,
      isFetched: true,
      isFetching: false,
      isFetchedAfterMount: true,
      isInitialLoading: false,
      isLoading: false,
      isLoadingError: false,
      isPaused: false,
      isRefetching: false,
      isRefetchError: false,
      isPending: false,
      isSuccess: true,
      isStale: false,
      status: 'success',
      failureCount: 0,
      failureReason: null,
      fetchStatus: 'idle',
      refetch: () =>
        new Promise(() => {
          return;
        }),
    }),
    useFetchSecurityPositionByClass: () => ({
      data: securityPositionByClassMock,
      dataUpdatedAt: Date.now(),
      error: null,
      errorUpdateCount: 0,
      errorUpdatedAt: Date.now(),
      isError: false,
      isFetched: true,
      isFetching: false,
      isFetchedAfterMount: true,
      isInitialLoading: false,
      isLoading: false,
      isLoadingError: false,
      isPaused: false,
      isRefetching: false,
      isRefetchError: false,
      isPending: false,
      isSuccess: true,
      isStale: false,
      status: 'success',
      failureCount: 0,
      failureReason: null,
      fetchStatus: 'idle',
      refetch: () =>
        new Promise(() => {
          return;
        }),
    }),
    useFetchPerformance: () => ({
      data: mockPerformanceOverPeriods,
      dataUpdatedAt: Date.now(),
      error: null,
      errorUpdateCount: 0,
      errorUpdatedAt: Date.now(),
      isError: false,
      isFetched: true,
      isFetching: false,
      isFetchedAfterMount: true,
      isInitialLoading: false,
      isLoading: false,
      isLoadingError: false,
      isPaused: false,
      isRefetching: false,
      isRefetchError: false,
      isPending: false,
      isSuccess: true,
      isStale: false,
      status: 'success',
      failureCount: 0,
      failureReason: null,
      fetchStatus: 'idle',
      refetch: () =>
        new Promise(() => {
          return;
        }),
    }),
    useFetchRentability: () => ({
      data: mockRentabilityOverPeriods,
      dataUpdatedAt: Date.now(),
      error: null,
      errorUpdateCount: 0,
      errorUpdatedAt: Date.now(),
      isError: false,
      isFetched: true,
      isFetching: false,
      isFetchedAfterMount: true,
      isInitialLoading: false,
      isLoading: false,
      isLoadingError: false,
      isPaused: false,
      isRefetching: false,
      isRefetchError: false,
      isPending: false,
      isSuccess: true,
      isStale: false,
      status: 'success',
      failureCount: 0,
      failureReason: null,
      fetchStatus: 'idle',
      refetch: () =>
        new Promise(() => {
          return;
        }),
    }),
    useFetchStockEarnings: () => ({
      data: mockStockEarningsOverPeriods,
      dataUpdatedAt: Date.now(),
      error: null,
      errorUpdateCount: 0,
      errorUpdatedAt: Date.now(),
      isError: false,
      isFetched: true,
      isFetching: false,
      isFetchedAfterMount: true,
      isInitialLoading: false,
      isLoading: false,
      isLoadingError: false,
      isPaused: false,
      isRefetching: false,
      isRefetchError: false,
      isPending: false,
      isSuccess: true,
      isStale: false,
      status: 'success',
      failureCount: 0,
      failureReason: null,
      fetchStatus: 'idle',
      refetch: () =>
        new Promise(() => {
          return;
        }),
    }),
    useFetchPerformanceHistory: () => ({
      data: mockRentabilityHistory,
      dataUpdatedAt: Date.now(),
      error: null,
      errorUpdateCount: 0,
      errorUpdatedAt: Date.now(),
      isError: false,
      isFetched: true,
      isFetching: false,
      isFetchedAfterMount: true,
      isInitialLoading: false,
      isLoading: false,
      isLoadingError: false,
      isPaused: false,
      isRefetching: false,
      isRefetchError: false,
      isPending: false,
      isSuccess: true,
      isStale: false,
      status: 'success',
      failureCount: 0,
      failureReason: null,
      fetchStatus: 'idle',
      refetch: () =>
        new Promise(() => {
          return;
        }),
    }),
    useFetchWithdrawalDeposits: () => ({
      data: mockWithdrawalDepositsOverPeriods,
      dataUpdatedAt: Date.now(),
      error: null,
      errorUpdateCount: 0,
      errorUpdatedAt: Date.now(),
      isError: false,
      isFetched: true,
      isFetching: false,
      isFetchedAfterMount: true,
      isInitialLoading: false,
      isLoading: false,
      isLoadingError: false,
      isPaused: false,
      isRefetching: false,
      isRefetchError: false,
      isPending: false,
      isSuccess: true,
      isStale: false,
      status: 'success',
      failureCount: 0,
      failureReason: null,
      fetchStatus: 'idle',
      refetch: () =>
        new Promise(() => {
          return;
        }),
    }),
  };

  return (
    <RequestHooksProvider {...providerProps}>
      <Story />
    </RequestHooksProvider>
  );
};
